version: "3.8"

services:
  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      ACCOMMODATION_SERVICE_HOST: ${ACCOMMODATION_SERVICE_HOST}
      ACCOMMODATION_SERVICE_PORT: ${ACCOMMODATION_SERVICE_PORT}
      RESERVATION_SERVICE_HOST: ${RESERVATION_SERVICE_HOST}
      RESERVATION_SERVICE_PORT: ${RESERVATION_SERVICE_PORT}
      RATING_SERVICE_HOST: ${RATING_SERVICE_HOST}
      RATING_SERVICE_PORT: ${RATING_SERVICE_PORT}
    networks:
      - network

  auth_service:
    image: auth_service
    container_name: auth_service
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    restart: on-failure
    environment:
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
    depends_on:
      - auth_db
    networks:
      - network

  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: on-failure
    environment:
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      CREATE_RESERVATION_COMMAND_SUBJECT: ${CREATE_RESERVATION_COMMAND_SUBJECT}
      CREATE_RESERVATION_REPLY_SUBJECT: ${CREATE_RESERVATION_REPLY_SUBJECT}
      RESERVATION_SERVICE_HOST: ${RESERVATION_SERVICE_HOST}
      RESERVATION_SERVICE_PORT: ${RESERVATION_SERVICE_PORT}
    depends_on:
      - user_db
    networks:
      - network

  accommodation_service:
    image: accommodation_service
    container_name: accommodation_service
    build:
      context: .
      dockerfile: ./accommodation_service/Dockerfile
    restart: on-failure
    environment:
      ACCOMMODATION_DB_HOST: ${ACCOMMODATION_DB_HOST}
      ACCOMMODATION_DB_PORT: ${ACCOMMODATION_DB_PORT}
      ACCOMMODATION_SERVICE_PORT: ${ACCOMMODATION_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      CREATE_RESERVATION_COMMAND_SUBJECT: ${CREATE_RESERVATION_COMMAND_SUBJECT}
      CREATE_RESERVATION_REPLY_SUBJECT: ${CREATE_RESERVATION_REPLY_SUBJECT}
    depends_on:
      - accommodation_db
    networks:
      - network

  reservation_service:
    image: reservation_service
    container_name: reservation_service
    build:
      context: .
      dockerfile: ./reservation_service/Dockerfile
    restart: on-failure
    environment:
      RESERVATION_DB_HOST: ${RESERVATION_DB_HOST}
      RESERVATION_DB_PORT: ${RESERVATION_DB_PORT}
      RESERVATION_SERVICE_PORT: ${RESERVATION_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      CREATE_RESERVATION_COMMAND_SUBJECT: ${CREATE_RESERVATION_COMMAND_SUBJECT}
      CREATE_RESERVATION_REPLY_SUBJECT: ${CREATE_RESERVATION_REPLY_SUBJECT}
      ACCOMMODATION_SERVICE_HOST: ${ACCOMMODATION_SERVICE_HOST}
      ACCOMMODATION_SERVICE_PORT: ${ACCOMMODATION_SERVICE_PORT}
    depends_on:
      - reservation_db
    networks:
      - network

  rating_service:
    image: rating_service
    container_name: rating_service
    build:
      context: .
      dockerfile: ./rating_service/Dockerfile
    restart: on-failure
    environment:
      RATING_DB_HOST: ${RATING_DB_HOST}
      RATING_DB_PORT: ${RATING_DB_PORT}
      RATING_SERVICE_PORT: ${RATING_SERVICE_PORT}
      RESERVATION_SERVICE_HOST: ${RESERVATION_SERVICE_HOST}
      RESERVATION_SERVICE_PORT: ${RESERVATION_SERVICE_PORT}
    depends_on:
      - rating_db
    networks:
      - network

  auth_db:
    image: mongo
    container_name: auth_db
    volumes:
      - authDb:/data/db
    restart: on-failure
    ports:
      - 5001:27017
    networks:
      - network

  user_db:
    image: mongo
    container_name: user_db
    volumes:
      - userDb:/data/db
    restart: on-failure
    ports:
      - 5002:27017
    networks:
      - network

  accommodation_db:
    image: mongo
    container_name: accommodation_db
    volumes:
      - accommodationDb:/data/db
    restart: on-failure
    ports:
      - 5003:27017
    networks:
      - network

  reservation_db:
    image: mongo
    container_name: reservation_db
    volumes:
      - reservationDb:/data/db
    restart: on-failure
    ports:
      - 5004:27017
    networks:
      - network

  rating_db:
    image: mongo
    container_name: rating_db
    volumes:
      - ratingDb:/data/db
    restart: on-failure
    ports:
      - 5005:27017
    networks:
      - network

  nats:
    image: nats
    container_name: nats
    restart: on-failure
    networks:
      - network

volumes:
  authDb:
  userDb:
  accommodationDb:
  reservationDb:
  ratingDb:

networks:
  network:
    driver: bridge