// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: notification_service/notification_service.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotificationService_GetAllNotificationsForHost_FullMethodName  = "/notification.NotificationService/GetAllNotificationsForHost"
	NotificationService_GetAllNotificationsForGuest_FullMethodName = "/notification.NotificationService/GetAllNotificationsForGuest"
	NotificationService_AcknowledgeNotification_FullMethodName     = "/notification.NotificationService/AcknowledgeNotification"
	NotificationService_InsertNotification_FullMethodName          = "/notification.NotificationService/InsertNotification"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	GetAllNotificationsForHost(ctx context.Context, in *IdRequestHost, opts ...grpc.CallOption) (*GetAllNotificationsForHostResponse, error)
	GetAllNotificationsForGuest(ctx context.Context, in *IdRequestGuest, opts ...grpc.CallOption) (*GetAllNotificationsForHostResponse, error)
	AcknowledgeNotification(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*Notification, error)
	InsertNotification(ctx context.Context, in *CreateNotification, opts ...grpc.CallOption) (*Notification, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) GetAllNotificationsForHost(ctx context.Context, in *IdRequestHost, opts ...grpc.CallOption) (*GetAllNotificationsForHostResponse, error) {
	out := new(GetAllNotificationsForHostResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetAllNotificationsForHost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetAllNotificationsForGuest(ctx context.Context, in *IdRequestGuest, opts ...grpc.CallOption) (*GetAllNotificationsForHostResponse, error) {
	out := new(GetAllNotificationsForHostResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetAllNotificationsForGuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) AcknowledgeNotification(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*Notification, error) {
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_AcknowledgeNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) InsertNotification(ctx context.Context, in *CreateNotification, opts ...grpc.CallOption) (*Notification, error) {
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_InsertNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	GetAllNotificationsForHost(context.Context, *IdRequestHost) (*GetAllNotificationsForHostResponse, error)
	GetAllNotificationsForGuest(context.Context, *IdRequestGuest) (*GetAllNotificationsForHostResponse, error)
	AcknowledgeNotification(context.Context, *Notification) (*Notification, error)
	InsertNotification(context.Context, *CreateNotification) (*Notification, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) GetAllNotificationsForHost(context.Context, *IdRequestHost) (*GetAllNotificationsForHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllNotificationsForHost not implemented")
}
func (UnimplementedNotificationServiceServer) GetAllNotificationsForGuest(context.Context, *IdRequestGuest) (*GetAllNotificationsForHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllNotificationsForGuest not implemented")
}
func (UnimplementedNotificationServiceServer) AcknowledgeNotification(context.Context, *Notification) (*Notification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeNotification not implemented")
}
func (UnimplementedNotificationServiceServer) InsertNotification(context.Context, *CreateNotification) (*Notification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertNotification not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_GetAllNotificationsForHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequestHost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetAllNotificationsForHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetAllNotificationsForHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetAllNotificationsForHost(ctx, req.(*IdRequestHost))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetAllNotificationsForGuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequestGuest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetAllNotificationsForGuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetAllNotificationsForGuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetAllNotificationsForGuest(ctx, req.(*IdRequestGuest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_AcknowledgeNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Notification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).AcknowledgeNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_AcknowledgeNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).AcknowledgeNotification(ctx, req.(*Notification))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_InsertNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).InsertNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_InsertNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).InsertNotification(ctx, req.(*CreateNotification))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllNotificationsForHost",
			Handler:    _NotificationService_GetAllNotificationsForHost_Handler,
		},
		{
			MethodName: "GetAllNotificationsForGuest",
			Handler:    _NotificationService_GetAllNotificationsForGuest_Handler,
		},
		{
			MethodName: "AcknowledgeNotification",
			Handler:    _NotificationService_AcknowledgeNotification_Handler,
		},
		{
			MethodName: "InsertNotification",
			Handler:    _NotificationService_InsertNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification_service/notification_service.proto",
}
